/* Jeux de runes  */
package POO;

import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/** * * @author Denis */
public class Main extends javax.swing.JFrame {
 
    /**   * Creates new form Main;     */
    public Main() throws IOException {
        initComponents();
        setIcon();
        initRunes();
    }
    
    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
    }

    private void initRunes() {
        listeRunes=new Rune[nbRunes];
        
        String nomsRunes[]={
             "01-fehu"
            ,"02-uruz"
            ,"03-thurisaz"
            ,"04-ansuz"
            ,"05-raido"
            ,"06-kauna"
            ,"07-gebo"
            ,"08-wunjo"
            ,"09-haglaz"
            ,"10-naudiz"
            ,"11-isaz"
            ,"12-jeran"
            ,"13-iwaz"
            ,"14-pertho"
            ,"15-algiz"
            ,"16-sowilo"
            ,"17-tiwaz"
            ,"18-berkanan"
            ,"19-ehwaz"
            ,"20-mannaz"
            ,"21-laukaz"
            ,"22-ingwaz"
            ,"23-dagaz"
            ,"24-othalan"    
        } ;
        
        int nRune=0;
        for (int i=0; i<nbRunes;i++){
            listeRunes[i]=new Rune( "/images/"+nomsRunes[nRune]+".png","/images/stele.png", true,nRune,nomsRunes[nRune]);
            listeRunes[i].tournerVersDos();
            
            nRune++;
            if (nRune==nbRunes/2) nRune=0;
         }
        melanger();
        afficherRunesAvecEvt();
    }
    
    private void afficherRunesAvecEvt(){
        
        for (int i=0; i<nbRunes;i++){
        boiteRunes.add(listeRunes[i]);
        
            // Créer un écouteur d'événement sur une rune
            listeRunes[i].addMouseListener(new java.awt.event.MouseAdapter() {
               @Override
               public void mouseReleased(java.awt.event.MouseEvent evt){
                   runeMouseReleased(evt);
               }
            });
        }
    }
    
    private void runeMouseReleased(java.awt.event.MouseEvent evt){
        runeCliquee=(Rune) evt.getSource();
        filResultats=filResultats+"Numéro et nom de la rune: "+runeCliquee.getNomRune()+"\n";
        resultatsTfd.setText(filResultats);

       
//       if (runeCliquee.isCoteDos()) runeCliquee.tournerVersFace();
//       else runeCliquee.tournerVersDos();
        
        if (aRetourner){
            premiereRune.tournerVersDos();
            deuxiemeRune.tournerVersDos();
            aRetourner=false;            
        }
       
       if (nbClick==0){
           premiereRune=runeCliquee;
           nbClick=1;
           premiereRune.tournerVersFace();
           // Supprimer l'écouteur d'événement
           premiereRune.removeMouseListener(premiereRune.getMouseListeners()[0]);
       }
       else if(nbClick==1){
           deuxiemeRune=runeCliquee;
           nbClick=0;
           deuxiemeRune.tournerVersFace();
           if (deuxiemeRune.getId()!=premiereRune.getId()) {
               aRetourner=true;
               premiereRune.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent evt){
                        runeMouseReleased(evt);
                    }
                });
           }
           else {
                deuxiemeRune.removeMouseListener(deuxiemeRune.getMouseListeners()[0]);
                nbPairesRetournees+=2;
                filResultats=filResultats+"nbPairesRetournees: "+nbPairesRetournees/2+"\n";
                resultatsTfd.setText(filResultats);
                
                if (nbPairesRetournees>=nbRunes) {
                    new Message(this, true) ;
                    retournerToutesLesRunes();
                    boiteRunes.removeAll();
                    initRunes();
                    nbPairesRetournees=0;
                }
           }
       }
    };                

    private int auHasardEntre(int min, int max){
        int nbAlea=(int) ((max-min)*Math.random()+min);
        return nbAlea;
    }

    private void melanger(){
        Rune tmp;
        int indAlea;
        
        for (int i=0; i<nbRunes;i++){
            tmp=listeRunes[i];
            indAlea=auHasardEntre(i+1,listeRunes.length-1);
            listeRunes[i]=listeRunes[indAlea];
            listeRunes[indAlea]=tmp;
        }
    }

    private void retournerToutesLesRunes(){
        for (int i=0; i<nbRunes;i++){
            listeRunes[i].tournerVersDos();
        }
    };       
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boiteRunes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultatsTfd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boiteRunes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jeu de runes - retourner toutes les stèles, paire par paire, en cliquant dessus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        boiteRunes.setMinimumSize(new java.awt.Dimension(800, 500));
        boiteRunes.setPreferredSize(new java.awt.Dimension(1300, 600));
        boiteRunes.setLayout(new java.awt.GridLayout(4, 12));

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        resultatsTfd.setBackground(new java.awt.Color(216, 216, 216));
        resultatsTfd.setColumns(20);
        resultatsTfd.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        resultatsTfd.setRows(5);
        jScrollPane2.setViewportView(resultatsTfd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boiteRunes, javax.swing.GroupLayout.PREFERRED_SIZE, 1286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(boiteRunes, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private Rune [] listeRunes;
    private static int nbRunes=48;
    private Rune runeCliquee, premiereRune, deuxiemeRune;
    private int nbClick=0;
    private boolean aRetourner=false; 
    private int nbPairesRetournees=0;
    private String [] nomsRunes;
    private String filResultats="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boiteRunes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultatsTfd;
    // End of variables declaration//GEN-END:variables
}
